sudo: required
dist: trusty
notifications:
  email: false
branches:
 only:
   - master
language: python
python: "3.5"
cache:
 - pip

install:
 - sudo apt install python3-matplotlib
 - pip3 install -r requirements.txt

script:
 - nose2
